# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackhub', '0002_auto_20180926_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_tag',
            new_name='tags',
        ),
    ]
